### ISSUE TITLE
use more expressive code

### ISSUE THREAD

**Issue by fabriziomoscon** [ibanjb/Drag-n-drop#1]
Hi @ibanjb thanks for completing the test.

Could you re-evaluate this lines to use a cleaner way to create a boolean:
https://github.com/ibanjb/Drag-n-drop/blob/master/src/components/dragItem/index.js#L75-L78

**Comment by ibanjb** [comment]
Agree, that was a 'ugly way' to create a boolean using a condition, more cleaner will be something like:

const isEmpty = items.length === 0;

**TODO**: Improve quality code for the DragItem component

**Comment by ibanjb** [comment]
Done
