### ISSUE TITLE
use CSS-in-JS

### ISSUE THREAD

**Issue by fabriziomoscon** [ibanjb/Drag-n-drop#3]
Our team leverages extensively CSS-in-JS.
Could you try to apply `styled-components` to this block: 
https://github.com/ibanjb/Drag-n-drop/blob/master/src/components/dragItem/index.js#L21-L28

**Comment by ibanjb** [comment]
In my github's repo there is an example about how to use styled ccmponents (very very basic, was something to test server side rendering with node js -internal demo-):

https://github.com/ibanjb/SchemaValidator/blob/master/src/client/App.js 

**TODO**: Create a style component example for component User (for example)

**Comment by ibanjb** [comment]
Created a styled component for the .src/App.js
